version: "3.9"
name: twentibeauti
services:
  frontend:
    stdin_open: true
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: Frontend
    tty: true
    networks:
      - app-network
    volumes:
      - /app/node_modules
      - ./frontend:/var/www/html/
    expose:
      - "3000"
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: "php artisan serve --host=0.0.0.0 --port=9000"
    restart: unless-stopped
    container_name: Backend
    tty: true
    environment:
      SERVICE_NAME: laravel
      SERVICE_TAGS: dev
    networks:
      - app-network
    working_dir: /var/www/html/
    volumes:
      - ./backend:/var/www/html/
    expose:
      - "9000"
    ports:
      - "9000:9000"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password= --database=tb_my_twenti --execute \"SELECT * FROM users;\""
      interval: 10s
      timeout: 3s
      retries: 10
    

  db:
    image: mysql:latest
    restart: unless-stopped
    container_name: MySQL
    tty: true
    networks:
      - app-network
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: tb_my_twenti
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    volumes:
      - ./mysql/init.d/:/docker-entrypoint-initdb.d/


  nginx:
    image: nginx:1.17
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: nginx
    tty: true
    networks:
      - app-network
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

networks:
  app-network:
    driver: bridge

volumes:
  data:
    name: data