version: "3.9"
name: twentibeauti-backend
services:
  #PHP Service
  laravel:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: laravel
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: laravel
      SERVICE_TAGS: dev
    working_dir: /var/www/html/
    volumes:
      - ./:/var/www/html/
    networks:
      - app-network
    ports: 
      - "8000:8000"
  #Nginx Service
  webserver:
    depends_on:
      - laravel
    build:
      context: ./nginx
      dockerfile: nginx.dockerfile
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    networks:
      - app-network
  
#Docker Networks
networks:
  app-network:
    driver: bridge

volumes:
  mysql:
    driver: local
